all:
	@echo compiling my_coppy.
	@gcc copy.c lib_11.c -o my_copy
	@echo compiling my_tree.
	@gcc tree.c lib_11.c -o my_tree

copy:
	@echo compiling my_coppy.
	@gcc copy.c lib_11.c -o my_copy

tree:
	@echo compiling my_tree.
	@gcc tree.c lib_11.c -o my_tree
